# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapipostgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  strapi:
    build:
      context: ./strapi-backend
    container_name: strapi-backend
    environment:
      DATABASE_HOST: "192.168.0.102"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "strapipostgres"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      APP_KEYS: "CNsbNEvTODJjXJFF90a2ag==,Qy0xfoMHrk59GMBdu2rDQQ==,1ir6YLeLP7nQOFUBAd7iWw==,lYN2A7AHPil7Ww4i+nvPjg=="
      API_TOKEN_SALT: "f3aPBN/5t65JIp2BYkfRDw=="
      ADMIN_JWT_SECRET: "UzP937vdih/1U4EslKXvNw=="
      TRANSFER_TOKEN_SALT: "JrUkiw5jFd2y4BrD0684tQ=="
      DATABASE_CLIENT: "postgres"
      DATABASE_SSL: false
      JWT_SECRET: "7jHrE1qBxJWecPPPfIkAfw=="
    depends_on:
      - postgres
    ports:
      - "1337:1337"

  strapi_updater:
    build:
      context: ./strapi_updater
    environment:
        STRAPI_URL: "http://localhost:1337"
        # STRAPI_URL: "https://devstrapi.thedigitalacademy.co.za"
        # STRAPI_URL: "https://devportaladmin.thedigitalacademy.co.za"
        PORT: 10000
    depends_on:
      - strapi
    ports:
      - '10000:10000'

  # strapi_updater_mq:
  #   build:
  #     context: ./strapi_updater_mq
  #   environment:
        # STRAPI_URL: "http://localhost:1337"
        # STRAPI_URL: "https://devstrapi.thedigitalacademy.co.za"
        # STRAPI_URL: "https://devportaladmin.thedigitalacademy.co.za"
        # PORT: 10000
        # STRAPI_ENDPOINT: "api/micro-apps/"
        # STRAPI_UPDATER_MQ: "http://localhost:3001/update"
        # FILTERS: "?populate=*&pagination[pageSize]=10000"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3000:3000'
